SPIRITSKILLS = {
    "none": 0,
    "movespeedup": 1,
    "hypersmashattacks": 2,
    "jumpup": 4,
    "additionalmidairjump": 5,
    "easierdodging": 8,
    "easierperfectshield": 9,
    "superarmor": 10,
    "slowsuperarmor": 11,
    "trade-offattacksup": 12,
    "trade-offdefenseup": 13,
    "trade-offspeedup": 14,
    "trade-offabilityup": 15,
    "critical-healthattackup": 16,
    "critical-healthdefenseup": 17,
    "critical-healthstatsup": 18,
    "criticalimmunity": 19,
    "autoheal": 20,
    "poisonimmunity": 21,
    "poisondamagereduced": 22,
    "poisonheals": 23,
    "lava-floorimmunity": 24,
    "sticky-floorimmunity": 25,
    "beamswordequipped": 26,
    "lipsstickequipped": 27,
    "starrodequipped": 28,
    "oreclubequipped": 29,
    "raygunequipped": 31,
    "superscopeequipped": 32,
    "drillequipped": 34,
    "greenshellequipped": 35,
    "backshieldequipped": 38,
    "bunnyhoodequipped": 39,
    "madeofmetal": 40,
    "mouthfulofcurry": 41,
    "franklinbadgeequipped": 42,
    "fairybottleequipped": 44,
    "fireflowerequipped": 45,
    "freezieequipped": 46,
    "ramblinevilmushroomequipped": 47,
    "killingedgeequipped": 48,
    "physicalattackup": 50,
    "weaponattackup": 51,
    "fistattackup": 52,
    "footattackup": 53,
    "auraattackup": 54,
    "magicattackup": 55,
    "psiattackup": 56,
    "fire&explosionattackup": 58,
    "electricattackup": 60,
    "energy-shotattackup": 61,
    "water&iceattackup": 62,
    "magicresistup": 63,
    "psiresistup": 64,
    "fire/explosionresistup": 66,
    "electricresistup": 69,
    "energy-shotresistup": 70,
    "water/freezingresistup": 72,
    "auraresistup": 73,
    "zap-floorimmunity": 74,
    "slumberimmunity": 75,
    "ice-floorimmunity": 76,
    "fallingimmunity": 77,
    "buryimmunity": 78,
    "brakingabilityup": 79,
    "landinglagdown": 81,
    "lightweight": 82,
    "shielddamageup": 83,
    "airattackup": 84,
    "airdefenseup": 85,
    "neutralspecialup": 86,
    "sidespecialup": 87,
    "upspecialup": 88,
    "downspecialup": 89,
    "strongthrow": 90,
    "unflinchingchargedsmashes": 91,
    "toss&meteor": 92,
    "criticalhitup": 94,
    "swimmer": 95,
    "shielddurabilityup": 96,
    "improvedescape": 97,
    "batteringitemsup": 101,
    "shootingitemsup": 102,
    "thrownitemsup": 103,
    "koshealdamage": 104,
    "invincibilityaftereating": 105,
    "statsupaftereating": 106,
    "first-strikeadvantage": 108,
    "runningstart": 110,
    "fastfinalsmashmeter": 112,
    "instadrop": 113,
    "healingshield": 114,
    "floatyjumps": 117,
    "irreversiblecontrols": 119,
    "transformationdurationup": 121,
    "undamagedattackup": 122,
    "undamagedspeedup": 123,
    "undamagedattack&speedup": 124,
    "impactrun": 128,
    "lava-floorresist": 130,
    "itemgravitation": 131,
    "chanceofdoublefinalsmash": 133,
    "doublefinalsmash": 134,
    "giant": 138,
    "dashattackup": 139,
    "armorknight": 140,
    "energyshotattack/resistanceup": 142,
    "hammerdurationup": 143,
    "boomerangequipped": 144,
    "perfect-shieldreflect": 151,
    "weaponattack&movespeedup": 152,
    "shootingattackup": 153,
    "screen-flipimmunity": 156,
    "fogimmunity": 157,
    "gravity-changeimmunity": 158,
    "staminaup": 159,
    "strong-windresist": 160,
    "strong-windimmunity": 161,
    "critical-healthhealing": 162,
    "special-movepowerup": 163,
    "bob-ombequipped": 165,
    "hotheadequipped": 166,
    "superleafequipped": 167,
    "superlaunchstarequipped": 168,
    "beastballequipped": 169,
    "deathsscytheequipped": 170,
    "mr.saturnequipped": 171,
    "uniraequipped": 172,
    "rocketbeltequipped": 173,
    "blackholeequipped": 174,
    "statsupupaftereating": 176,
    "critical-healthstatsupup": 178,
    "criticalhitupup": 179,
    "greatautoheal": 180,
    "steeldiverequipped": 181,
    "bananagunequipped": 182,
    "rageblasterequipped": 183,
    "staffequipped": 184,
    "firebarequipped": 185,
    "screwattackequipped": 186,
    "bomberequipped": 187,
    "giantkiller": 213,
    "metalkiller": 214,
    "assistkiller": 215,
    "jamfscharge": 216,
    "weaponresistup": 217,
    "itemautograb": 227,
    "teampowerup": 228,
    "poisonpowerup": 230,
    "criticalfastfinalsmashmeterupup": 231,
    "critical-healthhealingupup": 232,
    "criticalsupergiant": 233,
    "mouthfulofcurryupup": 234,
    "finalsmashup": 235,
    "criticalhealing&metal": 236,
}

SKILLSLOTS = {
    "none": 0,
    "movespeedup": 1,
    "hypersmashattacks": 1,
    "jumpup": 1,
    "additionalmidairjump": 2,
    "easierdodging": 1,
    "easierperfectshield": 1,
    "superarmor": 3,
    "slowsuperarmor": 2,
    "trade-offattacksup": 1,
    "trade-offdefenseup": 1,
    "trade-offspeedup": 1,
    "trade-offabilityup": 1,
    "critical-healthattackup": 1,
    "critical-healthdefenseup": 1,
    "critical-healthstatsup": 1,
    "criticalimmunity": 2,
    "autoheal": 2,
    "poisonimmunity": 2,
    "poisondamagereduced": 1,
    "poisonheals": 3,
    "lava-floorimmunity": 2,
    "sticky-floorimmunity": 2,
    "beamswordequipped": 1,
    "lipsstickequipped": 1,
    "starrodequipped": 1,
    "oreclubequipped": 3,
    "raygunequipped": 2,
    "superscopeequipped": 2,
    "drillequipped": 1,
    "greenshellequipped": 1,
    "backshieldequipped": 1,
    "bunnyhoodequipped": 1,
    "madeofmetal": 1,
    "mouthfulofcurry": 2,
    "franklinbadgeequipped": 2,
    "fairybottleequipped": 1,
    "fireflowerequipped": 1,
    "freezieequipped": 1,
    "ramblinevilmushroomequipped": 1,
    "killingedgeequipped": 1,
    "physicalattackup": 1,
    "weaponattackup": 1,
    "fistattackup": 1,
    "footattackup": 1,
    "auraattackup": 1,
    "magicattackup": 1,
    "psiattackup": 1,
    "fire&explosionattackup": 1,
    "electricattackup": 1,
    "energy-shotattackup": 1,
    "water&iceattackup": 1,
    "magicresistup": 1,
    "psiresistup": 1,
    "fire/explosionresistup": 1,
    "electricresistup": 1,
    "energy-shotresistup": 1,
    "water/freezingresistup": 1,
    "auraresistup": 1,
    "zap-floorimmunity": 2,
    "slumberimmunity": 1,
    "ice-floorimmunity": 2,
    "fallingimmunity": 1,
    "buryimmunity": 1,
    "brakingabilityup": 1,
    "landinglagdown": 1,
    "lightweight": 1,
    "shielddamageup": 1,
    "airattackup": 1,
    "airdefenseup": 1,
    "neutralspecialup": 1,
    "sidespecialup": 1,
    "upspecialup": 1,
    "downspecialup": 1,
    "strongthrow": 1,
    "unflinchingchargedsmashes": 2,
    "toss&meteor": 1,
    "criticalhitup": 1,
    "swimmer": 1,
    "shielddurabilityup": 1,
    "improvedescape": 1,
    "batteringitemsup": 1,
    "shootingitemsup": 1,
    "thrownitemsup": 1,
    "koshealdamage": 2,
    "invincibilityaftereating": 2,
    "statsupaftereating": 1,
    "first-strikeadvantage": 2,
    "runningstart": 2,
    "fastfinalsmashmeter": 2,
    "instadrop": 2,
    "healingshield": 2,
    "floatyjumps": 1,
    "irreversiblecontrols": 2,
    "transformationdurationup": 1,
    "undamagedattackup": 1,
    "undamagedspeedup": 1,
    "undamagedattack&speedup": 1,
    "impactrun": 1,
    "lava-floorresist": 1,
    "itemgravitation": 1,
    "chanceofdoublefinalsmash": 2,
    "doublefinalsmash": 3,
    "giant": 2,
    "dashattackup": 1,
    "armorknight": 2,
    "energyshotattack/resistanceup": 2,
    "hammerdurationup": 1,
    "boomerangequipped": 1,
    "perfect-shieldreflect": 1,
    "weaponattack&movespeedup": 2,
    "shootingattackup": 1,
    "screen-flipimmunity": 2,
    "fogimmunity": 2,
    "gravity-changeimmunity": 2,
    "staminaup": 1,
    "strong-windresist": 1,
    "strong-windimmunity": 2,
    "critical-healthhealing": 2,
    "special-movepowerup": 1,
    "bob-ombequipped": 1,
    "hotheadequipped": 2,
    "superleafequipped": 1,
    "superlaunchstarequipped": 1,
    "beastballequipped": 1,
    "deathsscytheequipped": 1,
    "mr.saturnequipped": 1,
    "uniraequipped": 1,
    "rocketbeltequipped": 1,
    "blackholeequipped": 2,
    "statsupupaftereating": 2,
    "critical-healthstatsupup": 2,
    "criticalhitupup": 2,
    "greatautoheal": 3,
    "steeldiverequipped": 2,
    "bananagunequipped": 1,
    "rageblasterequipped": 1,
    "staffequipped": 1,
    "firebarequipped": 1,
    "screwattackequipped": 2,
    "bomberequipped": 1,
    "giantkiller": 1,
    "metalkiller": 1,
    "assistkiller": 1,
    "jamfscharge": 2,
    "weaponresistup": 2,
    "itemautograb": 1,
    "teampowerup": 2,
    "poisonpowerup": 3,
    "criticalfastfinalsmashmeterupup": 3,
    "critical-healthhealingupup": 3,
    "criticalsupergiant": 3,
    "mouthfulofcurryupup": 3,
    "finalsmashup": 2,
    "criticalhealing&metal": 2,
}
SPIRITSKILLTABLE = {
    "none": "none",
    "toatk": "trade-offattacksup",
    "toattack": "trade-offattacksup",
    "toattacks": "trade-offattacksup",
    "toak": "trade-offattacksup",
    "tok": "trade-offattacksup",
    "tod": "trade-offdefenseup",
    "todefense": "trade-offdefenseup",
    "todefenses": "trade-offdefenseup",
    "tos": "trade-offspeedup",
    "tospeed": "trade-offspeedup",
    "tomovespeed": "trade-offspeedup",
    "toms": "trade-offspeedup",
    "tomovementspeed": "trade-offspeedup",
    "toa": "trade-offabilityup",
    "toability": "trade-offabilityup",
    "bestsingleslotspiritinthegame": "trade-offabilityup",
    "tostats": "trade-offabilityup",
    "tradeoffstats": "trade-offabilityup",
    "toab": "trade-offabilityup",
    "ms": "movespeedup",
    "movespeed": "movespeedup",
    "move": "movespeedup",
    "movementspeed": "movespeedup",
    "speed": "movespeedup",
    "fast": "movespeedup",
    "speedup": "movespeedup",
    "movespeedup": "movespeedup",
    "mvs": "movespeedup",
    "hsa": "hypersmashattacks",
    "hyper": "hypersmashattacks",
    "hypersmashes": "hypersmashattacks",
    "hypersmashattack": "hypersmashattacks",
    "smashattack": "hypersmashattacks",
    "smashes": "hypersmashattacks",
    "jump": "jumpup",
    "jumphigh": "jumpup",
    "highjump": "jumpup",
    "higherjump": "jumpup",
    "higherjumps": "jumpup",
    "bigjump": "jumpup",
    "bigjumps": "jumpup",
    "amj": "additionalmidairjump",
    "triplejump": "additionalmidairjump",
    "3jumps": "additionalmidairjump",
    "extrajump": "additionalmidairjump",
    "morejumps": "additionalmidairjump",
    "anotherjump": "additionalmidairjump",
    "extramidairjump": "additionalmidairjump",
    "anothermidairjump": "additionalmidairjump",
    "emj": "additionalmidairjump",
    "3j": "additionalmidairjump",
    "jumpmore": "additionalmidairjump",
    "ezd": "easierdodging",
    "easydodge": "easierdodging",
    "easierdodge": "easierdodging",
    "ezdodge": "easierdodging",
    "easydodging": "easierdodging",
    "overratedspirit": "easierdodging",
    "ed": "easierdodging",
    "ezp": "easierperfectshield",
    "easyp": "easierperfectshield",
    "ep": "easierperfectshield",
    "easyparry": "easierperfectshield",
    "easierparry": "easierperfectshield",
    "easyparries": "easierperfectshield",
    "easierperfect": "easierperfectshield",
    "easyperfect": "easierperfectshield",
    "easyshield": "easierperfectshield",
    "moreparries": "easierperfectshield",
    "sa": "superarmor",
    "heavyarmor": "superarmor",
    "armor": "superarmor",
    "armour": "superarmor",
    "ssa": "slowsuperarmor",
    "slowarmor": "slowsuperarmor",
    "slowsuperarmour": "slowsuperarmor",
    "slowarmour": "slowsuperarmor",
    "slowheavyarmor": "slowsuperarmor",
    "cha": "critical-healthattackup",
    "chatk": "critical-healthattackup",
    "ch-a": "critical-healthattackup",
    "ch-atk": "critical-healthattackup",
    "ch-attacks": "critical-healthattackup",
    "chattacks": "critical-healthattackup",
    "chattack": "critical-healthattackup",
    "chattacks": "critical-healthattackup",
    "crit-hpattack": "critical-healthattackup",
    "crit-hpattacks": "critical-healthattackup",
    "crit-hp-attack": "critical-healthattackup",
    "crit-hp-attacks": "critical-healthattackup",
    "critical-healthattack": "critical-healthattackup",
    "critical-healthattacks": "critical-healthattackup",
    "chd": "critical-healthdefenseup",
    "chdefense": "critical-healthdefenseup",
    "ch-d": "critical-healthdefenseup",
    "ch-defense": "critical-healthdefenseup",
    "chdefense": "critical-healthdefenseup",
    "crit-hpdefense": "critical-healthdefenseup",
    "crit-hp-defense": "critical-healthdefenseup",
    "critical-healthdefense": "critical-healthdefenseup",
    "chs": "critical-healthstatsup",
    "cha": "critical-healthstatsup",
    "chstats": "critical-healthstatsup",
    "chability": "critical-healthstatsup",
    "ch-s": "critical-healthstatsup",
    "ch-stats": "critical-healthstatsup",
    "ch-ability": "critical-healthstatsup",
    "chstats": "critical-healthstatsup",
    "crit-hpstats": "critical-healthstatsup",
    "crit-hp-stats": "critical-healthstatsup",
    "critical-healthstats": "critical-healthstatsup",
    "critical-healthability": "critical-healthstatsup",
    "ci": "criticalimmunity",
    "criti": "criticalimmunity",
    "criticalimmune": "criticalimmunity",
    "critinvincible": "criticalimmunity",
    "criticalinvincible": "criticalimmunity",
    "critstar": "criticalimmunity",
    "crit-i": "criticalimmunity",
    "a": "autoheal",
    "auto": "autoheal",
    "lesserautoheal": "autoheal",
    "ah": "autoheal",
    "smallautoheal": "autoheal",
    "autohealing": "autoheal",
    "bruh": "poisonimmunity",
    "pi": "poisonimmunity",
    "poisonimmune": "poisonimmunity",
    "poisonresist": "poisonimmunity",
    "why": "poisondamagereduced",
    "pdr": "poisondamagereduced",
    "poisonreduced": "poisondamagereduced",
    "poisonweak": "poisondamagereduced",
    "ph": "poisonheals",
    "poisonheal": "poisonheals",
    "poisonhealing": "poisonheals",
    "poisonabsorb": "poisonheals",
    "lfi": "lava-floorimmunity",
    "lavaimmune": "lava-floorimmunity",
    "lavaresist": "lava-floorimmunity",
    "deez": "lava-floorimmunity",
    "sfi": "sticky-floorimmunity",
    "stfu": "sticky-floorimmunity",
    "stickyresist": "sticky-floorimmunity",
    "stickyimmune": "sticky-floorimmunity",
    "beam": "beamswordequipped",
    "beamsword": "beamswordequipped",
    "lazersword": "beamswordequipped",
    "lip": "lipsstickequipped",
    "lipstick": "lipsstickequipped",
    "flower": "lipsstickequipped",
    "flowersword": "lipsstickequipped",
    "flowerstick": "lipsstickequipped",
    "starrod": "starrodequipped",
    "kirbyrod": "starrodequipped",
    "starstaff": "starrodequipped",
    "rod": "starrodequipped",
    "ore": "oreclubequipped",
    "club": "oreclubequipped",
    "oreclub": "oreclubequipped",
    "rockclub": "oreclubequipped",
    "eyeclub": "oreclubequipped",
    "ray": "raygunequipped",
    "raygun": "raygunequipped",
    "lazergun": "raygunequipped",
    "lazer": "raygunequipped",
    "pew": "raygunequipped",
    "scope": "superscopeequipped",
    "superscope": "superscopeequipped",
    "sniper": "superscopeequipped",
    "supersniper": "superscopeequipped",
    "superscope": "superscopeequipped",
    "drill": "drillequipped",
    "drillgun": "drillequipped",
    "shell": "greenshellequipped",
    "green": "greenshellequipped",
    "greenshell": "greenshellequipped",
    "koopashell": "greenshellequipped",
    "koopa": "greenshellequipped",
    "backshield": "backshieldequipped",
    "shield": "backshieldequipped",
    "bunny": "bunnyhoodequipped",
    "bnuny": "bunnyhoodequipped",
    "rabbit": "bunnyhoodequipped",
    "bunnyhood": "bunnyhoodequipped",
    "hood": "bunnyhoodequipped",
    "orchidirl": "bunnyhoodequipped",
    "mom": "madeofmetal",
    "metal": "madeofmetal",
    "becomemetal": "madeofmetal",
    "curry": "mouthfulofcurry",
    "spicy": "mouthfulofcurry",
    "currybreath": "mouthfulofcurry",
    "firebreath": "mouthfulofcurry",
    "mouthofcurry": "mouthfulofcurry",
    "badge": "franklinbadgeequipped",
    "franklin": "franklinbadgeequipped",
    "franklinbadge": "franklinbadgeequipped",
    "dogwater": "franklinbadgeequipped",
    "fire": "fireflowerequipped",
    "fireflower": "fireflowerequipped",
    "freezie": "freezieequipped",
    "freezy": "freezieequipped",
    "freeze": "freezieequipped",
    "ice": "freezieequipped",
    "iceberg": "freezieequipped",
    "mushroom": "ramblinevilmushroomequipped",
    "ramblinevilmushroom": "ramblinevilmushroomequipped",
    "evilmushroom": "ramblinevilmushroomequipped",
    "ramblin": "ramblinevilmushroomequipped",
    "ramblinmushroom": "ramblinevilmushroomequipped",
    "shroom": "ramblinevilmushroomequipped",
    "killingedge": "killingedgeequipped",
    "redsword": "killingedgeequipped",
    "sword": "killingedgeequipped",
    "nuts": "killingedgeequipped",
    "phys": "physicalattackup",
    "physup": "physicalattackup",
    "physical": "physicalattackup",
    "physicalattack": "physicalattackup",
    "weap": "weaponattackup",
    "weapon": "weaponattackup",
    "weaponup": "weaponattackup",
    "weapup": "weaponattackup",
    "weaponattack": "weaponattackup",
    "fist": "fistattackup",
    "punch": "fistattackup",
    "fistup": "fistattackup",
    "hand": "fistattackup",
    "foot": "footattackup",
    "kick": "footattackup",
    "leg": "footattackup",
    "footup": "footattackup",
    "footattack": "footattackup",
    "aura": "auraattackup",
    "blue": "auraattackup",
    "auraup": "auraattackup",
    "auraattack": "auraattackup",
    "magic": "magicattackup",
    "magicup": "magicattackup",
    "magicattack": "magicattackup",
    "majic": "magicattackup",
    "spell": "magicattackup",
    "mage": "magicattackup",
}

TRANSLATION_TABLE_CHARACTER_TRANSPLANT = {
    "kingk.rool": "king k rool",
    "krool": "king k rool",
    "palu": "palutena",
    "drmario": "dr mario",
    "incin": "incineroar",
    "diddy": "diddy kong",
    "koopaling": "bowser jr",
    "plant": "piranha plant",
    "mk": "meta knight",
    "icies": "ice climbers",
    "mac": "little mac",
    "ganon": "ganondorf",
    "pacman": "pac-man",
    "pac": "pac-man",
    "bayo": "bayonetta",
    "mm": "mega man",
    "mega": "mega man",
    "r.o.b.": "rob",
    "dsamus": "dark samus",
    "pt": "pokemon trainer",
    "gunner": "mii gunner",
    "dh": "duck hunt",
    "puff": "jigglypuff",
    "zss": "zero suit samus",
    "dpit": "dark pit",
    "brawler": "mii brawler",
    "gameandwatch": "mr game & watch",
    "g&w": "mr game & watch",
    "dk": "donkey kong",
    "falcon": "captain falcon",
    "dedede": "king dedede",
    "d3": "king dedede",
    "yink": "young link",
    "rosa": "rosalina & luma",
    "rosalina": "rosalina & luma",
    "miisword": "mii swordfighter",
    "sword": "mii swordfighter",
    "wft": "wii fit trainer",
    "wiifit": "wii fit trainer",
    "tink": "toon link",
    "banjo & kazooie": "banjo",
    "banjoandkazooie": "banjo",
}
SECTIONS = {
    "Near": 7,
    "Offensive": 7,
    "Grounded": 7,
    "Attack Out Cliff": 6,
    "Dash": 7,
    "Return To Cliff": 6,
    "Air Offensive": 6,
    "Cliffer": 6,
    "Feint Master": 7,
    "Feint Counter": 7,
    "Feint Shooter": 7,
    "Catcher": 7,
    "100 Attacker": 6,
    "100 Keeper": 6,
    "Attack Cancel": 6,
    "Smash Holder": 7,
    "Dash Attacker": 7,
    "Critical Hitter": 6,
    "Meteor Smasher": 6,
    "Shield Master": 7,
    "Just Shield Master": 6,
    "Shield Catch Master": 6,
    "Item Collector": 5,
    "Item Throw to Target": 5,
    "Dragoon Collector": 4,
    "Smash Ball Collector": 4,
    "Hammer Collector": 4,
    "Special Flagger": 4,
    "Item Swinger": 5,
    "Homerun Batter": 4,
    "Club Swinger": 4,
    "Death Swinger": 4,
    "Item Shooter": 5,
    "Carrier Breaker": 5,
    "Charger": 5,
    "Appeal": 5,
    "Advantageous Fighter": 14,
    "Weaken Fighter": 14,
    "Revenge": 14,
    "Stage Enemy": 14,
    "Forward Tilt": 10,
    "Up Tilt": 10,
    "Down Tilt": 10,
    "Forward Smash": 10,
    "Up Smash": 10,
    "Down Smash": 10,
    "Neutral Special": 10,
    "Side Special": 10,
    "Up Special": 10,
    "Down Special": 10,
    "Forward Air": 9,
    "Back Air": 9,
    "Up Air": 9,
    "Down Air": 9,
    "Neutral Special Air": 9,
    "Side Special Air": 9,
    "Up Special Air": 9,
    "Down Special Air": 9,
    "Front Air Dodge": 8,
    "Back Air Dodge": 8,
    "APPEAL_HI": 7,
    "APPEAL_LW": 7,
}